all:
	@echo configGUI python3 dummy makefile
clean:
	@echo configGUI python3 dummy clean target
install:
	@echo configGUI python3 dummy install target
uninstall:
	@echo configGUI python3 dummy uninstall target
